### ISSUE TITLE
Arrow missing in dropdown menu for text/numeric concepts operators

### ISSUE THREAD

**Issue by JLRaisaro** [lca1/medco-connector#75]
When dragging and dropping a concept for text or numeric filter, there is an arrow missing in the dropdown menu of the possible operators

<img width="960" alt="Screen Shot 2021-02-15 at 14 01 18" src="https://user-images.githubusercontent.com/24383576/107949944-52cee380-6f96-11eb-893c-6dceb2e88b17.png">

**Comment by mickmis** [comment]
Same as ldsec/glowing-bear-medco#47
