### ISSUE TITLE
Unconsistent numbering of ontology elements

### ISSUE THREAD

**Issue by Fasjul** [lca1/medco-connector#87]
Some ontology elements have a coded id (C89, A30...) as prefix of the descriptive name, some have it as suffix.

**Comment by mickmis** [comment]
Where does this come from? Is this inconsistency present in the original data?

**Comment by Fasjul** [comment]
Yes, the original terminologies are a mess. I fixed this and found other (minor) problems in the terminologies, opening a new issue
